[build]
command = "npm run build"
publish = ".next"

[functions]
included_files = [
  "next.config.js",
  "next-i18next.config.js",
  "public/locales/**",
]

[[plugins]]
package = "@netlify/plugin-nextjs"


[[redirects]]
from = "/api/*"
to = "http://blackmamba-services-production.eba-m9amxsfq.us-east-2.elasticbeanstalk.com/rest/:splat"
status = 200

[[redirects]]
from = "/images/*"
to = "https://s3.us-east-2.amazonaws.com/blackmamba-services-production/:splat"
status = 200
