[build]
command = "npm run build"
publish = ".next"

[functions]
included_files = [
  "next.config.js",
  "next-i18next.config.js",
  "public/locales/**",
]

[[plugins]]
package = "@netlify/plugin-nextjs"
