[build]
command = "npm run build"
publish = ".next"

[functions]
included_files = [
  "next.config.mjs",
  "public/locales/en/*.json",
  "/var/task/next-i18next.config.js",
]


[[plugins]]
package = "@netlify/plugin-nextjs"
