[build]
command = "npm run build"
publish = ".next"

[functions]
node_bundler = "esbuild"
included_files = [
  "next.config.mjs",
  "next-i18next.config.cjs",
  "public/locales/en/*.json",
  "/var/task/next-i18next.config.cjs",
]


[[plugins]]
package = "@netlify/plugin-nextjs"
