[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
node_bundler = "esbuild"
included_files = ["next-i18next.config.cjs", "public/locales/en/*.json"]
