import Team from './Team';
import Tournament from './Tournament';

type TournamentPlayerStats = {
  assists: number;
  assistsPerGame: number;
  blockedShots: number;
  blockedShotsPerGame: number;
  defensiveRebounds: number;
  defensiveReboundsPerGame: number;
  doubleDouble: number;
  fieldGoalPerGame: number;
  fieldGoalPercentage: number;
  freeThrowAttempts: number;
  freeThrowMade: number;
  freeThrowMadePerGame: number;
  freeThrowPerGame: number;
  freeThrowPercentage: number;
  gamesPlayed: number;
  id: string;
  offensiveRebounds: number;
  offensiveReboundsPerGame: number;
  personalFouls: number;
  pointsPerGame: number;
  quadrupleDouble: number;
  reboundsPerGame: number;
  round: number;
  steals: number;
  stealsPerGame: number;
  team: Team;
  threePointAttempts: number;
  threePointMade: number;
  threePointPerGame: number;
  threePointPercentage: number;
  totalPoints: number;
  totalRebounds: number;
  tournament: Tournament;
  tripleDouble: number;
  turnovers: number;
  turnoversPerGame: number;
  twoPointAttempts: number;
  twoPointMade: number;
  twoPointPerGame: number;
  twoPointPercentage: number;
};

export default TournamentPlayerStats;
